// <auto-generated />
namespace HattVidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populate_moves_users_membershiptypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_moves_users_membershiptypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201702012309094_populate_moves_users_membershiptypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
