// <auto-generated />
namespace HattVidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_columns_back : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_columns_back));
        
        string IMigrationMetadata.Id
        {
            get { return "201702050735008_add_columns_back"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
