// <auto-generated />
namespace HattVidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class model_making : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_making));
        
        string IMigrationMetadata.Id
        {
            get { return "201702030548584_model_making"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
